/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./components/home/Banner.vue')['default']
    BaseButton: typeof import('./components/shared/BaseButton.vue')['default']
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    Episode: typeof import('~icons/ep/isode')['default']
    EpisodeSection: typeof import('./components/home/EpisodeSection.vue')['default']
    'Episódios': typeof import('./components/home/Episódios.vue')['default']
    'EpisódiosSection': typeof import('~icons/ep/isódios-section')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    Footer: typeof import('./components/home/footer.vue')['default']
    Header: typeof import('./components/home/header.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    HomeBanner: typeof import('./components/home/HomeBanner.vue')['default']
    Location: typeof import('./components/home/location.vue')['default']
    LocationSection: typeof import('./components/home/locationSection.vue')['default']
    MdiAlien: typeof import('~icons/mdi/alien')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Personagens: typeof import('./components/home/Personagens.vue')['default']
    PersonagensSection: typeof import('./components/home/PersonagensSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
