/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/shared/BaseButton.vue')['default']
    ButtonPrimary: typeof import('./components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./components/shared/ButtonSecondary.vue')['default']
    Episode: typeof import('./components/home/episode.vue')['default']
    EpisodeInfo: typeof import('./components/episode/episodeInfo.vue')['default']
    EpisodeSection: typeof import('./components/home/EpisodeSection.vue')['default']
    Footer: typeof import('./components/home/Footer.vue')['default']
    Header: typeof import('./components/home/Header.vue')['default']
    Heading1: typeof import('./components/shared/Heading1.vue')['default']
    Heading2: typeof import('./components/shared/Heading2.vue')['default']
    HomeBanner: typeof import('./components/home/HomeBanner.vue')['default']
    Location: typeof import('./components/home/location.vue')['default']
    LocationSection: typeof import('./components/home/locationSection.vue')['default']
    MoreEpisode: typeof import('./components/episode/moreEpisode.vue')['default']
    MorePerson: typeof import('./components/person/morePerson.vue')['default']
    Personagens: typeof import('./components/home/Personagens.vue')['default']
    PersonagensSection: typeof import('./components/home/PersonagensSection.vue')['default']
    PersonInfo: typeof import('./components/person/personInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
